### ISSUE TITLE
MISSING DATA: Accelerometer

### ISSUE THREAD

**Issue by RileyLazarou** [TeamINTERACT/IngestScripts#8]
There's accel data missing. Specifically:

- wave 0 saskatoon (406)
- wave 1 victoria (212)
- wave 1 vancouver (376)
- wave 1 saskatoon (448)
- wave 1 montreal (395, 396)

Also "missing" is the accel data for "Montreal REM" (947, 948) (idk what this is, but it was in Zoe's spreadsheet).

The tarball contained these directories:

- study_212  # empty
- study_376  # empty
- study_395  # empty
- study_396  # contains output-000001.csv and output-000002.csv
- study_406  # empty
- study_448  # empty
- study_947  # contains output-000001.csv and output-000002.csv
- study_948  # contains output-000001.csv and output-000002.csv

As you can see, these correspond to the missing accel data, but most of them are empty. The `output-00000?.csv` files seem to be accelerometer data, but they're in a different format from the other accel files. There is overlap in the user_ids and device_ids between the two files. Clarification regarding why the files are in the format (and how to reconcile them), and why five of the studies have no data (and how to get it) is required

**Comment by walkabilly** [comment]
Ya. I'm pretty sure that those data were removed on the Ethica side and they just sent us an empty file because it was on their list. We had a conversation about deleting those files a long time ago. I think these data will need to be move from either `permanent_archive` or `raw_data_vault` into the new data structure.

**Comment by RileyLazarou** [comment]
Ok good to know, I can fetch this data from the old `permanent_archive`
