### ISSUE TITLE
MISSING DATA: GPS

### ISSUE THREAD

**Issue by RileyLazarou** [TeamINTERACT/IngestScripts#9]
All GPS data _files_ are accounted for, but several of them are empty, including:

- montreal/wave_01/ethica/395/395_gps.csv
- saskatoon/wave_00/ethica/406/406_gps.csv 
- saskatoon/wave_01/ethica/448/448_gps.csv
- vancouver/wave_01/ethica/376/376_gps.csv
- victoria/wave_01/ethica/212/212_gps.csv

Similarly, montreal wave 1 study 396 (fr) only has 18 records in its GPS file.

Other issues:

- cohesion 2.2 (study 2760) (has 0 records)
- Montreal rem (study 947) (has 11 records)
- Montreal rem (study 948) (has 291 records)

**Comment by walkabilly** [comment]
Same thing here as the accel data. W1 for all cities needs to be moved from `permanent_archive` or `raw_data_vault`.
